Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Get-GeminiDotfilesRoot {
    return Split-Path -Parent $PSScriptRoot
}

function Get-WorkspaceRoot {
    return Split-Path -Parent (Get-GeminiDotfilesRoot)
}

function Get-SourceMap {
    $root = Get-GeminiDotfilesRoot
    $localPath = Join-Path $root 'source-map.local.json'
    $basePath = if (Test-Path -LiteralPath $localPath) { $localPath } else { Join-Path $root 'source-map.json' }
    return Get-Content -Raw $basePath | ConvertFrom-Json
}

function Get-SourceMapValue {
    param([Parameter(Mandatory = $true)][string]$PathKey)

    $value = Get-SourceMap
    foreach ($part in ($PathKey -split '\.')) {
        $value = $value.$part
    }
    return [string]$value
}

function Get-GeminiHome {
    return Join-Path $HOME (Get-SourceMapValue -PathKey 'global.geminiHomeDirName')
}

function Get-GeminiContextPath {
    return Join-Path (Get-GeminiHome) (Get-SourceMapValue -PathKey 'global.contextFileName')
}

function Get-GeminiSettingsPath {
    return Join-Path (Get-GeminiHome) (Get-SourceMapValue -PathKey 'global.settingsFileName')
}

function Ensure-Directory {
    param([Parameter(Mandatory = $true)][string]$Path)
    New-Item -ItemType Directory -Force -Path $Path | Out-Null
}

function Get-CanonicalRepoPath {
    param([Parameter(Mandatory = $true)][string]$Name)
    return Join-Path (Get-WorkspaceRoot) $Name
}

function Get-MarkdownSection {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Heading
    )

    $content = Get-Content -Raw $Path
    $escapedHeading = [regex]::Escape($Heading)
    $pattern = "(?ms)^$escapedHeading\r?\n.*?(?=^##\s|\z)"
    $match = [regex]::Match($content, $pattern)
    if (-not $match.Success) {
        throw "Heading '$Heading' not found in $Path"
    }
    return $match.Value.TrimEnd()
}

function Write-GeneratedGlobalGemini {
    $root = Get-GeminiDotfilesRoot
    $map = Get-SourceMap
    $outputPath = Join-Path $root 'generated\global\GEMINI.md'
    Ensure-Directory -Path (Split-Path -Parent $outputPath)

    $claudeRoot = Get-CanonicalRepoPath -Name $map.canonical.claudeDotfilesRepo
    $securityRoot = Get-CanonicalRepoPath -Name $map.canonical.securityBaselineRepo
    $tokenGuardRoot = Get-CanonicalRepoPath -Name $map.canonical.tokenGuardRepo
    $claudeGlobal = Join-Path $claudeRoot 'claude\CLAUDE.md'
    $claudePolicies = Join-Path $claudeRoot 'claude\policies.md'
    $securitySnippet = Join-Path $securityRoot 'configs\claude-code\CLAUDE.md.snippet'
    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss K'

    $lines = @(
        '# Global Gemini Instructions',
        '',
        "> Generated by `gemini-dotfiles/scripts/bootstrap` on $timestamp.",
        '',
        'Claude remains the canonical source of truth. This file translates the portable global Claude rules into Gemini CLI''s default `GEMINI.md` memory location.',
        '',
        '## Canonical Sources',
        '',
        ('- `' + $claudeGlobal + '`'),
        ('- `' + $claudePolicies + '`'),
        ('- `' + $securitySnippet + '`'),
        ('- `' + (Join-Path $tokenGuardRoot 'README.md') + '`'),
        '',
        '## Gemini Operating Model',
        '',
        '- Treat this file as the global Gemini memory baseline.',
        '- Prefer repo-local `GEMINI.md` wrappers that import `CLAUDE.md` or `AGENTS.md` instead of duplicating project instructions.',
        '- Do not mirror machine-local Claude settings files.',
        '',
        '## Portable Rules',
        ''
    )

    foreach ($heading in $map.translation.globalGeminiSections) {
        $lines += Get-MarkdownSection -Path $claudeGlobal -Heading $heading
        $lines += ''
    }

    $lines += @(
        '## Security Baseline Reference',
        '',
        ('Portable security rules also come from `' + $securitySnippet + '`.'),
        'Project-specific protected-path guidance should still come from repo-local security files.',
        '',
        '## Detailed Reference',
        '',
        ('For procedures not copied into this file, read `' + $claudePolicies + '` on demand.')
    )

    Set-Content -LiteralPath $outputPath -Value ($lines -join [Environment]::NewLine)
    return $outputPath
}

function New-LinkOrCopy {
    param(
        [Parameter(Mandatory = $true)][string]$Source,
        [Parameter(Mandatory = $true)][string]$Target
    )

    Ensure-Directory -Path (Split-Path -Parent $Target)

    if (Test-Path -LiteralPath $Target) {
        $backup = "$Target.pre-gemini-dotfiles.bak"
        if (-not (Test-Path -LiteralPath $backup)) {
            Move-Item -LiteralPath $Target -Destination $backup
        } else {
            Remove-Item -LiteralPath $Target -Force -Recurse
        }
    }

    try {
        New-Item -ItemType SymbolicLink -Path $Target -Target $Source -Force | Out-Null
        return 'linked'
    } catch {
        Copy-Item -LiteralPath $Source -Destination $Target -Force
        return 'copied'
    }
}

function Merge-ManagedSettings {
    param([Parameter(Mandatory = $true)][string]$Path)

    Ensure-Directory -Path (Split-Path -Parent $Path)
    if (-not (Test-Path -LiteralPath $Path)) {
        Set-Content -LiteralPath $Path -Value '{}' -NoNewline
    }

    $currentRaw = Get-Content -Raw $Path
    $current = if ($currentRaw.Trim()) { $currentRaw | ConvertFrom-Json -AsHashtable } else { @{} }
    $managed = @{
        general = @{
            defaultApprovalMode = 'default'
            plan = @{
                enabled = $true
                modelRouting = $true
            }
        }
        privacy = @{
            usageStatisticsEnabled = $false
        }
        context = @{
            fileName = 'GEMINI.md'
        }
        security = @{
            environmentVariableRedaction = @{
                enabled = $true
            }
        }
    }

    function Merge-Hashtable {
        param(
            [Parameter(Mandatory = $true)][hashtable]$Base,
            [Parameter(Mandatory = $true)][hashtable]$Override
        )

        $result = @{}
        foreach ($key in $Base.Keys) { $result[$key] = $Base[$key] }
        foreach ($key in $Override.Keys) {
            if ($result[$key] -is [hashtable] -and $Override[$key] -is [hashtable]) {
                $result[$key] = Merge-Hashtable -Base $result[$key] -Override $Override[$key]
            } else {
                $result[$key] = $Override[$key]
            }
        }
        return $result
    }

    $merged = Merge-Hashtable -Base $current -Override $managed
    Set-Content -LiteralPath $Path -Value ($merged | ConvertTo-Json -Depth 10)
}

function Ensure-PowerShellGemFunction {
    $profilePath = $PROFILE.CurrentUserAllHosts
    Ensure-Directory -Path (Split-Path -Parent $profilePath)
    if (-not (Test-Path -LiteralPath $profilePath)) {
        New-Item -ItemType File -Path $profilePath -Force | Out-Null
    }

    $content = Get-Content -Raw $profilePath
    if ($content -notmatch '(?m)^function gem \{') {
        Add-Content -LiteralPath $profilePath -Value @"

function gem {
    gemini --approval-mode=yolo @args
}
"@
    }
}

function Write-ProjectGeminiWrapper {
    param([Parameter(Mandatory = $true)][string]$ProjectRoot)

    $target = Join-Path $ProjectRoot 'GEMINI.md'
    if (Test-Path -LiteralPath $target) {
        return $target
    }

    $lines = @(
        '# Gemini Project Context',
        '',
        'This repository is still Claude-first. Gemini CLI should load the canonical project instructions from the existing root files below instead of creating a competing instruction source.',
        ''
    )
    if (Test-Path -LiteralPath (Join-Path $ProjectRoot 'AGENTS.md')) {
        $lines += '@./AGENTS.md'
    }
    if (Test-Path -LiteralPath (Join-Path $ProjectRoot 'CLAUDE.md')) {
        $lines += '@./CLAUDE.md'
    }
    Set-Content -LiteralPath $target -Value ($lines -join [Environment]::NewLine)
    return $target
}

