#!/usr/bin/env bash
set -euo pipefail

get_gemini_dotfiles_root() {
  cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd
}

get_workspace_root() {
  cd "$(get_gemini_dotfiles_root)/.." && pwd
}

get_python_cmd() {
  if command -v python3 >/dev/null 2>&1; then
    printf 'python3\n'
  else
    printf 'python\n'
  fi
}

get_source_map_path() {
  local local_override
  local_override="$(get_gemini_dotfiles_root)/source-map.local.json"
  if [[ -f "$local_override" ]]; then
    printf '%s\n' "$local_override"
  else
    printf '%s\n' "$(get_gemini_dotfiles_root)/source-map.json"
  fi
}

source_map_value() {
  local key_path="$1"
  SOURCE_MAP_PATH="$(get_source_map_path)" \
  SOURCE_MAP_KEY_PATH="$key_path" \
  "$(get_python_cmd)" -c '
import json
import os

value = json.load(open(os.environ["SOURCE_MAP_PATH"], "r", encoding="utf-8"))
for part in os.environ["SOURCE_MAP_KEY_PATH"].split("."):
    value = value[part]
print(value)
'
}

get_canonical_repo_path() {
  local repo_name="$1"
  printf '%s/%s\n' "$(get_workspace_root)" "$repo_name"
}

workspace_path_from_source_map() {
  local key_path="$1"
  printf '%s/%s\n' "$(get_workspace_root)" "$(source_map_value "$key_path")"
}

ensure_dir() {
  mkdir -p "$1"
}

get_user_bin_dir() {
  printf '%s/.local/bin\n' "$HOME"
}

get_gemini_home() {
  printf '%s/%s\n' "$HOME" "$(source_map_value "global.geminiHomeDirName")"
}

get_gemini_context_path() {
  printf '%s/%s\n' "$(get_gemini_home)" "$(source_map_value "global.contextFileName")"
}

get_gemini_settings_path() {
  printf '%s/%s\n' "$(get_gemini_home)" "$(source_map_value "global.settingsFileName")"
}

markdown_section() {
  local path="$1"
  local heading="$2"
  awk -v heading="$heading" '
    $0 == heading { print; capture=1; next }
    capture && /^## / { exit }
    capture { print }
  ' "$path"
}

write_generated_global_gemini() {
  local root output claude_root security_root token_guard_root claude_global claude_policies security_snippet timestamp
  root="$(get_gemini_dotfiles_root)"
  output="$root/generated/global/GEMINI.md"
  ensure_dir "$(dirname "$output")"

  claude_root="$(get_canonical_repo_path "$(source_map_value "canonical.claudeDotfilesRepo")")"
  security_root="$(get_canonical_repo_path "$(source_map_value "canonical.securityBaselineRepo")")"
  token_guard_root="$(get_canonical_repo_path "$(source_map_value "canonical.tokenGuardRepo")")"
  claude_global="$claude_root/claude/CLAUDE.md"
  claude_policies="$claude_root/claude/policies.md"
  security_snippet="$security_root/configs/claude-code/CLAUDE.md.snippet"
  timestamp="$(date '+%Y-%m-%d %H:%M:%S %z')"

  {
    printf '# Global Gemini Instructions\n\n'
    printf '> Generated by `gemini-dotfiles/scripts/bootstrap` on %s.\n\n' "$timestamp"
    printf 'Claude remains the canonical source of truth. This file translates the portable global Claude rules into Gemini CLI''s default `GEMINI.md` memory location.\n\n'
    printf '## Canonical Sources\n\n'
    printf -- '- `%s`\n' "$claude_global"
    printf -- '- `%s`\n' "$claude_policies"
    printf -- '- `%s`\n' "$security_snippet"
    printf -- '- `%s`\n\n' "$token_guard_root/README.md"
    printf '## Gemini Operating Model\n\n'
    printf -- '- Treat this file as the global Gemini memory baseline.\n'
    printf -- '- Prefer repo-local `GEMINI.md` wrappers that import `CLAUDE.md` or `AGENTS.md` instead of duplicating project instructions.\n'
    printf -- '- Do not mirror machine-local Claude settings files.\n\n'
    printf '## Portable Rules\n\n'
  } > "$output"

  local sections=(
    "## Git & Commits"
    "## Security Essentials"
    "## Token Optimization"
    "## Research-First Protocol"
    "## 3-Layer Memory (see policies.md § Memory Architecture)"
    "## Process Improvement"
    "## New Project Standards"
  )

  local heading
  for heading in "${sections[@]}"; do
    markdown_section "$claude_global" "$heading" >> "$output"
    printf '\n\n' >> "$output"
  done

  {
    printf '## Security Baseline Reference\n\n'
    printf 'Portable security rules also come from `%s`.\n' "$security_snippet"
    printf 'Project-specific protected-path guidance should still come from repo-local security files.\n\n'
    printf '## Detailed Reference\n\n'
    printf 'For procedures not copied into this file, read `%s` on demand.\n' "$claude_policies"
  } >> "$output"

  printf '%s\n' "$output"
}

link_or_copy() {
  local source="$1"
  local target="$2"
  ensure_dir "$(dirname "$target")"
  if [[ -L "$target" && "$(readlink "$target")" == "$source" ]]; then
    printf 'linked\n'
    return 0
  fi
  if [[ -e "$target" || -L "$target" ]]; then
    local backup="${target}.pre-gemini-dotfiles.bak"
    if [[ ! -e "$backup" ]]; then
      mv "$target" "$backup"
    else
      rm -rf "$target"
    fi
  fi
  if ln -s "$source" "$target" 2>/dev/null; then
    printf 'linked\n'
  else
    if [[ -d "$source" ]]; then
      cp -R "$source" "$target"
    else
      cp "$source" "$target"
    fi
    printf 'copied\n'
  fi
}

merge_managed_settings() {
  local settings_path="$1"
  ensure_dir "$(dirname "$settings_path")"
  touch "$settings_path"
  SETTINGS_PATH="$settings_path" "$(get_python_cmd)" - <<'PY'
import json
import os
from pathlib import Path

path = Path(os.environ["SETTINGS_PATH"])
raw = path.read_text(encoding="utf-8").strip() if path.exists() else ""
try:
    current = json.loads(raw) if raw else {}
except json.JSONDecodeError:
    current = {}

managed = {
    "general": {
        "defaultApprovalMode": "default",
        "plan": {
            "enabled": True,
            "modelRouting": True,
        },
    },
    "privacy": {
        "usageStatisticsEnabled": False,
    },
    "context": {
        "fileName": "GEMINI.md",
    },
    "security": {
        "environmentVariableRedaction": {
            "enabled": True,
        },
    },
}

def merge(base, override):
    if isinstance(base, dict) and isinstance(override, dict):
        out = dict(base)
        for k, v in override.items():
            if k in out:
                out[k] = merge(out[k], v)
            else:
                out[k] = v
        return out
    return override

merged = merge(current, managed)
path.write_text(json.dumps(merged, indent=2) + "\n", encoding="utf-8")
PY
}

ensure_unix_alias() {
  local profile="$1"
  local alias_line="alias gem='gemini --approval-mode=yolo'"
  touch "$profile"
  if ! grep -Fqx "$alias_line" "$profile"; then
    printf '\n%s\n' "$alias_line" >> "$profile"
  fi
}

ensure_infisical_safe_wrapper_shell_wrapper() {
  local wrapper_repo="$1"
  local repo_wrapper="$wrapper_repo/bin/infisical-safe-wrapper.sh"
  local wrapper_dir wrapper_path

  if [[ ! -f "$repo_wrapper" ]]; then
    echo "Skipping infisical-safe-wrapper install because entrypoint is missing: $repo_wrapper"
    return 0
  fi

  wrapper_dir="$(get_user_bin_dir)"
  wrapper_path="$wrapper_dir/infisical-safe-wrapper"
  mkdir -p "$wrapper_dir"
  cat > "$wrapper_path" <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec bash "$repo_wrapper" "\$@"
EOF
  chmod +x "$wrapper_path"
  echo "Installed infisical-safe-wrapper shell wrapper in $wrapper_dir"
}

write_project_gemini_wrapper() {
  local project_root="${1:?project root required}"
  local target="$project_root/GEMINI.md"
  if [[ -e "$target" ]]; then
    printf '%s\n' "$target"
    return 0
  fi

  {
    printf '# Gemini Project Context\n\n'
    printf 'This repository is still Claude-first. Gemini CLI should load the canonical project instructions from the existing root files below instead of creating a competing instruction source.\n\n'
    if [[ -f "$project_root/AGENTS.md" ]]; then
      printf '@./AGENTS.md\n'
    fi
    if [[ -f "$project_root/CLAUDE.md" ]]; then
      printf '@./CLAUDE.md\n'
    fi
  } > "$target"

  printf '%s\n' "$target"
}
